"""anonymous_sessions

Revision ID: bd5571e1dadf
Revises: fed7be4275d0
Create Date: 2026-08-17 15:22:59.690650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5571e1dadf'
down_revision: Union[str, Sequence[str], None] = 'fed7be4275d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_datasets_session_id'), 'datasets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_session_id'), table_name='datasets')
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('datasets', 'session_id')
    # ### end Alembic commands ###
