"use client";

import { useRef } from "react";
import { motion } from "framer-motion";
import { Download, ImageDown } from "lucide-react";
import AreaRevenueChart from "./AreaRevenueChart";
import BarRevenueChart from "./BarRevenueChart";
import PieChart from "./PieChart";

interface ChartData { labels: string[]; values: number[]; }
interface ChartRendererProps { chartType: string | null; chartData: ChartData | null; }
export default function ChartRenderer({ chartType, chartData }: ChartRendererProps) { const chartRef = useRef<HTMLDivElement>(null); if (!chartType || chartType === "none" || !chartData) return null; function exportCsv() { if (!chartData) return; const csv = ["label,value", ...chartData.labels.map((label, index) => `${JSON.stringify(label)},${chartData.values[index] ?? ""}`)].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "charex-chart.csv"; link.click(); URL.revokeObjectURL(link.href); } function exportPng() { const svg = chartRef.current?.querySelector("svg"); if (!svg) return; const source = new XMLSerializer().serializeToString(svg); const image = new Image(); const url = URL.createObjectURL(new Blob([source], { type: "image/svg+xml" })); image.onload = () => { const canvas = document.createElement("canvas"); canvas.width = 1200; canvas.height = 700; const context = canvas.getContext("2d"); context?.drawImage(image, 0, 0, canvas.width, canvas.height); const link = document.createElement("a"); link.download = "charex-chart.png"; link.href = canvas.toDataURL("image/png"); link.click(); URL.revokeObjectURL(url); }; image.src = url; } const type = chartType.toLowerCase(); return <motion.div ref={chartRef} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="relative"><div className="absolute right-3 top-8 z-10 flex gap-1"><button onClick={exportPng} title="Export PNG" className="rounded-lg border border-white/[.08] bg-[#0a101a]/90 p-1.5 text-slate-400 transition hover:text-cyan-200"><ImageDown className="h-3.5 w-3.5" /></button><button onClick={exportCsv} title="Export CSV" className="rounded-lg border border-white/[.08] bg-[#0a101a]/90 p-1.5 text-slate-400 transition hover:text-cyan-200"><Download className="h-3.5 w-3.5" /></button></div>{type === "bar" ? <BarRevenueChart chartData={chartData} /> : type === "pie" ? <PieChart chartData={chartData} /> : <AreaRevenueChart chartData={chartData} />}</motion.div>; }
