"use client";

import { motion } from "framer-motion";
import { BrainCircuit, ChartNoAxesCombined, FileSearch, Sparkles } from "lucide-react";
import Container from "@/components/common/Container";

const items = [{ icon: FileSearch, title: "Understand every column", text: "Profile quality, types, gaps, and outliers before they become a blind spot." }, { icon: BrainCircuit, title: "Reason with your data", text: "Use plain language to uncover the why behind every metric and movement." }, { icon: ChartNoAxesCombined, title: "Tell the story visually", text: "Generate crisp charts and tables that make the signal unmistakable." }];

export default function Capabilities() { return <section className="relative py-28 sm:py-36"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_80%_40%,rgba(99,102,241,.12),transparent_28%)]" /><Container><div className="grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="inline-flex items-center gap-2 text-sm font-medium text-violet-200"><Sparkles className="h-4 w-4" /> Intelligence, without the busywork</div><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">A thoughtful analyst for every team.</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-400">From the first upload to the final recommendation, Char(t)ex makes complex analysis feel composed, quick, and surprisingly human.</p></div><div className="grid gap-4">{items.map((item, i) => { const Icon = item.icon; return <motion.article key={item.title} initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .1 }} whileHover={{ x: 6 }} className="group flex gap-5 rounded-2xl border border-white/10 bg-white/[.035] p-6 transition hover:border-violet-300/30 hover:bg-white/[.06]"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-violet-400/10 text-violet-200"><Icon className="h-5 w-5" /></div><div><h3 className="text-lg font-medium">{item.title}</h3><p className="mt-2 leading-7 text-slate-400">{item.text}</p></div></motion.article> })}</div></div></Container></section>; }
